var i = 0;
var t = 0;

var className = "priest";

tree[i] = "Discipline"; i++;
tree[i] = "Holy"; i++;
tree[i] = "Shadow"; i++;

i = 0;

talent[i] = [0, "Unbreakable Will", "", 5, 2, 1]; i++;
talent[i] = [0, "Wand Specialization", "", 5, 3, 1]; i++;
talent[i] = [0, "Silent Resolve", "changed", 5, 1, 2]; i++;
talent[i] = [0, "Improved Power Word: Fortitude", "", 2, 2, 2]; i++;
talent[i] = [0, "Improved Power Word: Shield", "", 3, 3, 2]; i++;
talent[i] = [0, "Martyrdom", "", 2, 4, 2]; i++;
talent[i] = [0, "Improved Inner Fire", "changedmoved", 3, 1, 3]; i++;
talent[i] = [0, "Inner Focus", "", 1, 2, 3]; i++;
talent[i] = [0, "Meditation", "", 3, 3, 3]; i++;
talent[i] = [0, "Absolution", "new", 2, 1, 4]; i++;
talent[i] = [0, "Mental Agility", "", 5, 2, 4]; i++;
talent[i] = [0, "Improved Mana Burn", "changed", 2, 4, 4]; i++;
talent[i] = [0, "Mental Strength", "", 5, 2, 5]; i++;
talent[i] = [0, "Divine Spirit", "", 1, 3, 5, [getTalentID("Meditation"), 3]]; i++;
talent[i] = [0, "Force of Will", "", 5, 3, 6]; i++;
talent[i] = [0, "Power Infusion", "", 1, 2, 7, [getTalentID("Mental Strength"), 5]]; i++;

treeStartStop[t] = i - 1;
t++;

talent[i] = [1, "Healing Focus", "", 2, 1, 1]; i++;
talent[i] = [1, "Improved Renew", "", 3, 2, 1]; i++;
talent[i] = [1, "Holy Specialization", "", 5, 3, 1]; i++;
talent[i] = [1, "Spell Warding", "", 5, 2, 2]; i++;
talent[i] = [1, "Divine Fury", "", 5, 3, 2]; i++;
talent[i] = [1, "Holy Nova", "", 1, 1, 3]; i++;
talent[i] = [1, "Blessed Recovery", "", 3, 2, 3]; i++;
talent[i] = [1, "Inspiration", "", 3, 4, 3]; i++;
talent[i] = [1, "Holy Reach", "changed", 2, 1, 4]; i++;
talent[i] = [1, "Improved Healing", "", 3, 2, 4]; i++;
talent[i] = [1, "Searing Light", "", 2, 3, 4, [getTalentID("Divine Fury"), 5]]; i++;
talent[i] = [1, "Improved Prayer of Healing", "", 2, 1, 5]; i++;
talent[i] = [1, "Spirit of Redemption", "", 1, 2, 5]; i++;
talent[i] = [1, "Spiritual Guidance", "", 5, 3, 5]; i++;
talent[i] = [1, "Spiritual Healing", "", 5, 3, 6]; i++;
talent[i] = [1, "Lightwell", "changed", 1, 2, 7, [getTalentID("Spirit of Redemption"), 1]]; i++;

treeStartStop[t] = i - 1;
t++;

talent[i] = [2, "Spirit Tap", "changed", 5, 2, 1]; i++;
talent[i] = [2, "Blackout", "", 5, 3, 1]; i++;
talent[i] = [2, "Shadow Affinity", "", 3, 1, 2]; i++;
talent[i] = [2, "Improved Shadow Word: Pain", "", 2, 2, 2]; i++;
talent[i] = [2, "Shadow Focus", "", 5, 3, 2]; i++;
talent[i] = [2, "Improved Psychic Scream", "changed", 2, 1, 3]; i++;
talent[i] = [2, "Improved Mind Blast", "", 5, 2, 3]; i++;
talent[i] = [2, "Mind Flay", "", 1, 3, 3]; i++;
talent[i] = [2, "Improved Fade", "changed", 2, 2, 4]; i++;
talent[i] = [2, "Shadow Reach", "changed", 2, 3, 4]; i++;
talent[i] = [2, "Shadow Weaving", "changed", 5, 4, 4]; i++;
talent[i] = [2, "Silence", "", 1, 1, 5, [getTalentID("Improved Psychic Scream"), 2]]; i++;
talent[i] = [2, "Vampiric Embrace", "", 1, 2, 5]; i++;
talent[i] = [2, "Improved Vampiric Embrace", "changed", 2, 3, 5, [getTalentID("Vampiric Embrace"), 1]]; i++;
talent[i] = [2, "Mind Melt", "new", 2, 4, 5]; i++;
talent[i] = [2, "Darkness", "", 5, 3, 6]; i++;
talent[i] = [2, "Shadowform", "", 1, 2, 7, [getTalentID("Vampiric Embrace"), 1]]; i++;

treeStartStop[t] = i - 1;
t++;

i = 0;


//DISCIPLINE

//Unbreakable Will - Discipline
rank[i] = [
		"Increases your chance to resist stun, fear, and silence effects by 3%.",
		"Increases your chance to resist stun, fear, and silence effects by 6%.",
		"Increases your chance to resist stun, fear, and silence effects by 9%.",
		"Increases your chance to resist stun, fear, and silence effects by 12%.",
		"Increases your chance to resist stun, fear, and silence effects by 15%."
		];
i++;
//Wand Specialization - Discipline
rank[i] = [
		"Increases your damage with Wands by 5%.",
		"Increases your damage with Wands by 10%.",
		"Increases your damage with Wands by 15%.",
		"Increases your damage with Wands by 20%.",
		"Increases your damage with Wands by 25%."
		];
i++;
//Silent Resolve - Discipline
rank[i] = [
		"Reduces the threat generated by your Holy and Discipline spells by 4% and reduces the chance your spell effects will be dispelled by 4%.",
		"Reduces the threat generated by your Holy and Discipline spells by 8% and reduces the chance your spell effects will be dispelled by 8%.",
		"Reduces the threat generated by your Holy and Discipline spells by 12% and reduces the chance your spell effects will be dispelled by 12%.",
		"Reduces the threat generated by your Holy and Discipline spells by 16% and reduces the chance your spell effects will be dispelled by 16%.",
		"Reduces the threat generated by your Holy and Discipline spells by 20% and reduces the chance your spell effects will be dispelled by 20%."
		];
i++;
//Improved Power Word: Fortitude - Discipline
rank[i] = [
		"Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 15%.",
		"Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 30%."
		];
i++;
//Improved Power Word: Shield - Discipline
rank[i] = [
		"Increases the damage absorbed by your Power Word: Shield by 5%.",
		"Increases the damage absorbed by your Power Word: Shield by 10%.",
		"Increases the damage absorbed by your Power Word: Shield by 15%."
		];
i++;
//Martyrdom - Discipline
rank[i] = [
		"Gives you a 50% chance to gain the Focused Casting effect that lasts for 6 seconds after being the victim of a melee or ranged critical strike.  The Focused Casting effect prevents you from losing casting time when taking damage and increases resistance to interrupt effects by 10%.",
		"Gives you a 100% chance to gain the Focused Casting effect that lasts for 6 seconds after being the victim of a melee or ranged critical strike.  The Focused Casting effect prevents you from losing casting time when taking damage and increases resistance to interrupt effects by 20%."
		];
i++;
//Improved Inner Fire - Discipline
rank[i] = [
		"Increases the armour bonus of your Inner Fire spell by 10% and its number of charges by 4.",
		"Increases the armour bonus of your Inner Fire spell by 20% and its number of charges by 8.",
		"Increases the armour bonus of your Inner Fire spell by 30% and its number of charges by 12."
		];
i++;
//Inner Focus - Discipline
rank[i] = [
		"Cast: instant.<br>When activated, reduces the mana cost of your next spell by 100% and increases its critical effect chance by 25% if it is capable of a critical effect.  (Cooldown: 3 minutes.)"
		];
i++;
//Meditation - Discipline
rank[i] = [
		"Allows 5% of your mana regeneration to continue while casting.",
		"Allows 10% of your mana regeneration to continue while casting.",
		"Allows 15% of your mana regeneration to continue while casting."
		];
i++;
//Absolution - Discipline
rank[i] = [
		"Reduces the mana cost of your Dispel Magic, Cure Disease, and Abolish Disease spells by 10%.",
		"Reduces the mana cost of your Dispel Magic, Cure Disease, and Abolish Disease spells by 20%."
		];
i++;
//Mental Agility - Discipline
rank[i] = [
		"Reduces the mana cost of your instant cast spells by 2%.",
		"Reduces the mana cost of your instant cast spells by 4%.",
		"Reduces the mana cost of your instant cast spells by 6%.",
		"Reduces the mana cost of your instant cast spells by 8%.",
		"Reduces the mana cost of your instant cast spells by 10%."
		];
i++;
//Improved Mana Burn - Discipline
rank[i] = [
		"Reduces the casting time of your Mana Burn spell by 0.5 seconds.",
		"Reduces the casting time of your Mana Burn spell by 1 second."
		];
i++;
//Mental Strength - Discipline
rank[i] = [
		"Increases your maximum mana by 2%.",
		"Increases your maximum mana by 4%.",
		"Increases your maximum mana by 6%.",
		"Increases your maximum mana by 8%.",
		"Increases your maximum mana by 10%."
		];
i++;
//Divine Spirit - Discipline
rank[i] = [
		"Cast: instant.<br>Range: 30 yards.<br>Cost: Y mana.<br>Holy power infuses the target, increasing their Spirit by X for 30 minutes.<br><br>[Rank 1: X = 17, Y = 285,<br>&nbsp;Rank 2: X = 23, Y = 420 (level 40),<br>&nbsp;Rank 3: X = 33, Y = 785 (level 50),<br>&nbsp;Rank 4: X = 40, Y = 970 (level 60).]"
		];
i++;
//Force of Will - Discipline
rank[i] = [
		"Increases the damage and critical strike chance of your offensive spells by 1%.",
		"Increases the damage and critical strike chance of your offensive spells by 2%.",
		"Increases the damage and critical strike chance of your offensive spells by 3%.",
		"Increases the damage and critical strike chance of your offensive spells by 4%.",
		"Increases the damage and critical strike chance of your offensive spells by 5%."
		];
i++;
//Power Infusion - Discipline
rank[i] = [
		"Cast: instant.<br>Range: 30 yards.<br>Cost: 20% of base mana.<br>Infuses the target with power, increasing their spell damage and healing by 20%.  Lasts 15 seconds.  (Cooldown: 3 minutes.)"
		];
i++;


//HOLY

//Healing Focus - Holy
rank[i] = [
		"Gives you a 35% chance to avoid interruption caused by damage while casting any healing spell.",
		"Gives you a 70% chance to avoid interruption caused by damage while casting any healing spell."
		];
i++;
//Improved Renew - Holy
rank[i] = [
		"Increases the amount healed by your Renew spell by 5%.",
		"Increases the amount healed by your Renew spell by 10%.",
		"Increases the amount healed by your Renew spell by 15%."
		];
i++;
//Holy Specialization - Holy
rank[i] = [
		"Increases the critical effect chance of your Holy spells by 1%.",
		"Increases the critical effect chance of your Holy spells by 2%.",
		"Increases the critical effect chance of your Holy spells by 3%.",
		"Increases the critical effect chance of your Holy spells by 4%.",
		"Increases the critical effect chance of your Holy spells by 5%."
		];
i++;
//Spell Warding - Holy
rank[i] = [
		"Reduces all spell damage taken by 2%.",
		"Reduces all spell damage taken by 4%.",
		"Reduces all spell damage taken by 6%.",
		"Reduces all spell damage taken by 8%.",
		"Reduces all spell damage taken by 10%."
		];
i++;
//Divine Fury - Holy
rank[i] = [
		"Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.1 seconds.",
		"Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.2 seconds.",
		"Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.3 seconds.",
		"Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.4 seconds.",
		"Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.5 seconds."
		];
i++;
//Holy Nova - Holy
rank[i] = [
		"Cast: instant.<br>Cost: B mana.<br>Causes an explosion of holy light around the caster, causing X to Y Holy damage to all enemy targets within 10 yards and healing all party members within 10 yards for Z to A.  These effects cause no threat.<br><br>[Rank 1: X = 29, &nbsp;&nbsp;Y = 34, &nbsp;&nbsp;Z = 54, &nbsp;&nbsp;A = 63, &nbsp;&nbsp;B = 185,<br>&nbsp;Rank 2: X = 52, &nbsp;&nbsp;Y = 61, &nbsp;&nbsp;Z = 89, &nbsp;&nbsp;A = 101, B = 290 (level 28),<br>&nbsp;Rank 3: X = 79, &nbsp;&nbsp;Y = 92, &nbsp;&nbsp;Z = 124, A = 143, B = 400 (level 36),<br>&nbsp;Rank 4: X = 110, Y = 127, Z = 165, A = 192, B = 520 (level 44),<br>&nbsp;Rank 5: X = 146, Y = 168, Z = 239, A = 276, B = 635 (level 52),<br>&nbsp;Rank 6: X = 181, Y = 209, Z = 302, A = 350, B = 750 (level 60).]"
		];
i++;
//Blessed Recovery - Holy
rank[i] = [
		"After being struck by a melee or ranged critical hit, heal 8% of the damage taken over 6 seconds.",
		"After being struck by a melee or ranged critical hit, heal 16% of the damage taken over 6 seconds.",
		"After being struck by a melee or ranged critical hit, heal 25% of the damage taken over 6 seconds."
		];
i++;
//Inspiration - Holy
rank[i] = [
		"Increases your target's armor by 8% for 15 seconds after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell.",
		"Increases your target's armor by 16% for 15 seconds after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell.",
		"Increases your target's armor by 25% for 15 seconds after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell."
		];
i++;
//Holy Reach - Holy
rank[i] = [
		"Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing, Holy Nova, and Lightwell spells by 10%.",
		"Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing, Holy Nova, and Lightwell spells by 20%."
		];
i++;
//Improved Healing - Holy
rank[i] = [
		"Reduces the mana cost of your Lesser Heal, Heal, and Greater Heal spells by 5%.",
		"Reduces the mana cost of your Lesser Heal, Heal, and Greater Heal spells by 10%.",
		"Reduces the mana cost of your Lesser Heal, Heal, and Greater Heal spells by 15%."
		];
i++;
//Searing Light - Holy
rank[i] = [
		"Increases the damage of your Smite and Holy Fire spells by 5%.",
		"Increases the damage of your Smite and Holy Fire spells by 10%."
		];
i++;
//Improved Prayer of Healing - Holy
rank[i] = [
		"Reduces the mana cost of your Prayer of Healing spell by 10%.",
		"Reduces the mana cost of your Prayer of Healing spell by 20%."
		];
i++;
//Spirit of Redemption - Holy
rank[i] = [
		"Upon death, the priest becomes the Spirit of Redemption for 10 seconds.  The Spirit of Redemption cannot move, attack, be attacked, or be targeted by any spells or effects.  While in this form the Priest can cast any healing spell free of cost.  When the effect ends, the Priest dies."
		];
i++;
//Spiritual Guidance - Holy
rank[i] = [
		"Increases spell damage and healing by up to 5% of your total Spirit.",
		"Increases spell damage and healing by up to 10% of your total Spirit.",
		"Increases spell damage and healing by up to 15% of your total Spirit.",
		"Increases spell damage and healing by up to 20% of your total Spirit.",
		"Increases spell damage and healing by up to 25% of your total Spirit."
		];
i++;
//Spiritual Healing - Holy
rank[i] = [
		"Increases the amount healed by your healing spells by 2%.",
		"Increases the amount healed by your healing spells by 4%.",
		"Increases the amount healed by your healing spells by 6%.",
		"Increases the amount healed by your healing spells by 8%.",
		"Increases the amount healed by your healing spells by 10%."
		];
i++;
//Lightwell - Holy
rank[i] = [
		"Cast: 1.5 seconds.<br>Cost: Y mana.<br>Creates a holy Lightwell near the Priest.  Members of your raid or party within 10 yards of the Lightwell restore X health every 2 seconds.  The Lightwell lasts for 20 seconds.  (Cooldown: 10 minutes.)<br><br>[Rank 1: X = 80, &nbsp;&nbsp;Y = 225,<br>&nbsp;Rank 2: X = 116, Y = 295 (level 50),<br>&nbsp;Rank 3: X = 160, Y = 365 (level 60).]"
		];
i++;


//SHADOW

//Spirit Tap - Shadow
rank[i] = [
		"Gives you a 20% chance to gain a 100% bonus to your Spirit after killing a target that yields experience.  For the duration, your mana will regenerate at a 50% rate while casting.  Lasts 15 seconds.<br><br>[Note: You no longer have to land the killing blow to trigger this effect, but you do need to have caused direct or channeled damage (DOTs don't count) to the target within 2 seconds of its death.]",
		"Gives you a 40% chance to gain a 100% bonus to your Spirit after killing a target that yields experience.  For the duration, your mana will regenerate at a 50% rate while casting.  Lasts 15 seconds.<br><br>[Note: You no longer have to land the killing blow to trigger this effect, but you do need to have caused direct or channeled damage (DOTs don't count) to the target within 2 seconds of its death.]",
		"Gives you a 60% chance to gain a 100% bonus to your Spirit after killing a target that yields experience.  For the duration, your mana will regenerate at a 50% rate while casting.  Lasts 15 seconds.<br><br>[Note: You no longer have to land the killing blow to trigger this effect, but you do need to have caused direct or channeled damage (DOTs don't count) to the target within 2 seconds of its death.]",
		"Gives you a 80% chance to gain a 100% bonus to your Spirit after killing a target that yields experience.  For the duration, your mana will regenerate at a 50% rate while casting.  Lasts 15 seconds.<br><br>[Note: You no longer have to land the killing blow to trigger this effect, but you do need to have caused direct or channeled damage (DOTs don't count) to the target within 2 seconds of its death.]",
		"Gives you a 100% chance to gain a 100% bonus to your Spirit after killing a target that yields experience.  For the duration, your mana will regenerate at a 50% rate while casting.  Lasts 15 seconds.<br><br>[Note: You no longer have to land the killing blow to trigger this effect, but you do need to have caused direct or channeled damage (DOTs don't count) to the target within 2 seconds of its death.]"
		];
i++;
//Blackout - Shadow
rank[i] = [
		"Gives your Shadow damage spells a 2% chance to stun the target for 3 seconds.",
		"Gives your Shadow damage spells a 4% chance to stun the target for 3 seconds.",
		"Gives your Shadow damage spells a 6% chance to stun the target for 3 seconds.",
		"Gives your Shadow damage spells a 8% chance to stun the target for 3 seconds.",
		"Gives your Shadow damage spells a 10% chance to stun the target for 3 seconds."
		];
i++;
//Shadow Affinity - Shadow
rank[i] = [
		"Reduces the threat generated by your Shadow spells by 8%.",
		"Reduces the threat generated by your Shadow spells by 16%.",
		"Reduces the threat generated by your Shadow spells by 25%."
		];
i++;
//Improved Shadow Word: Pain - Shadow
rank[i] = [
		"Increases the duration of your Shadow Word: Pain spell by 3 seconds.",
		"Increases the duration of your Shadow Word: Pain spell by 6 seconds."
		];
i++;
//Shadow Focus - Shadow
rank[i] = [
		"Reduces your target's chance to resist your Shadow spells by 2%.",
		"Reduces your target's chance to resist your Shadow spells by 4%.",
		"Reduces your target's chance to resist your Shadow spells by 6%.",
		"Reduces your target's chance to resist your Shadow spells by 8%.",
		"Reduces your target's chance to resist your Shadow spells by 10%."
		];
i++;
//Improved Psychic Scream - Shadow
rank[i] = [
		"Reduces the cooldown of your Psychic Scream spell by 3 seconds.",
		"Reduces the cooldown of your Psychic Scream spell by 6 seconds."
		];
i++;
//Improved Mind Blast - Shadow
rank[i] = [
		"Reduces the cooldown of your Mind Blast spell by 0.5 seconds.",
		"Reduces the cooldown of your Mind Blast spell by 1 seconds.",
		"Reduces the cooldown of your Mind Blast spell by 1.5 seconds.",
		"Reduces the cooldown of your Mind Blast spell by 2 seconds.",
		"Reduces the cooldown of your Mind Blast spell by 2.5 seconds."
		];
i++;
//Mind Flay - Shadow
rank[i] = [
		"Cast: channeled (3 seconds).<br>Range: 20 yards.<br>Cost: Y mana.<br>Assault the target's mind with Shadow energy, causing X Shadow damage over 3 seconds and slowing their movement speed by 50%.<br><br>[Rank 1: X = 75, &nbsp;&nbsp;Y = 45, <br>&nbsp;Rank 2: X = 126, Y = 70 (level 28),<br>&nbsp;Rank 3: X = 186, Y = 100 (level 36),<br>&nbsp;Rank 4: X = 261, Y = 135 (level 44),<br>&nbsp;Rank 5: X = 330, Y = 165 (level 52),<br>&nbsp;Rank 6: X = 426, Y = 205 (level 60).]"
		];
i++;
//Improved Fade - Shadow
rank[i] = [
		"Reduces the cooldown of your Fade ability by 3 seconds.  In addition, if Fade is used while in Shadowform, its duration is increased by 1 second and the threat generated by your other Shadow spells is reduced by 10% while it is active.<br><br>[Note: The duration and threat reduction components also apply to the Fade spell cast by the Transcendence (T2 set) 5-piece set bonus.]",
		"Reduces the cooldown of your Fade ability by 6 seconds.  In addition, if Fade is used while in Shadowform, its duration is increased by 2 seconds and the threat generated by your other Shadow spells is reduced by 20% while it is active.<br><br>[Note: The duration and threat reduction components also apply to the Fade spell cast by the Transcendence (T2 set) 5-piece set bonus.]"
		];
i++;
//Shadow Reach - Shadow
rank[i] = [
		"Increases the range of your Shadow damage spells by 10%.",
		"Increases the range of your Shadow damage spells by 20%."
		];
i++;
//Shadow Weaving - Shadow
rank[i] = [
		"Your Shadow damage spells have a 20% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 seconds.  Stacks up to 5 times.<br><br>[Note: This effect also triggers from and applies to procs from Feedback, Shadowguard, and Touch of Weakness.]",
		"Your Shadow damage spells have a 40% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 seconds.  Stacks up to 5 times.<br><br>[Note: This effect also triggers from and applies to procs from Feedback, Shadowguard, and Touch of Weakness.]",
		"Your Shadow damage spells have a 60% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 seconds.  Stacks up to 5 times.<br><br>[Note: This effect also triggers from and applies to procs from Feedback, Shadowguard, and Touch of Weakness.]",
		"Your Shadow damage spells have a 80% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 seconds.  Stacks up to 5 times.<br><br>[Note: This effect also triggers from and applies to procs from Feedback, Shadowguard, and Touch of Weakness.]",
		"Your Shadow damage spells have a 100% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 seconds.  Stacks up to 5 times.<br><br>[Note: This effect also triggers from and applies to procs from Feedback, Shadowguard, and Touch of Weakness.]"
		];
i++;
//Silence - Shadow
rank[i] = [
		"Cast: instant.<br>Range: 20 yards.<br>Cost: 225 mana.<br>Silences the target, preventing them from casting spells for 5 seconds.  (Cooldown: 45 seconds.)"
		];
i++;
//Vampiric Embrace - Shadow
rank[i] = [
		"Cast: instant.<br>Range: 30 yards.<br>Cost: 40 mana.<br>Afflicts your target with Shadow energy that causes all party members to be healed for 20% of any Shadow spell damage you deal to that target for 1 minute.  (Cooldown: 10 seconds.)"
		];
i++;
//Improved Vampiric Embrace - Shadow
rank[i] = [
		"Your Vampiric Embrace also causes party members to gain mana equal to 1% of the Shadow spell damage you deal to the target.",
		"Your Vampiric Embrace also causes party members to gain mana equal to 2% of the Shadow spell damage you deal to the target."
		];
i++;
//Mind Melt - Shadow
rank[i] = [
		"Increases the critcal strike chance of your Mind Blast spell by 2%.  When your Mind Blast spell critically hits, it confuses the victim, redirecting 60% of the threat caused by the spell to the victim's current target.",
		"Increases the critcal strike chance of your Mind Blast spell by 4%.  When your Mind Blast spell critically hits, it confuses the victim, redirecting 120% of the threat caused by the spell to the victim's current target."
		];
i++;
//Darkness - Shadow
rank[i] = [
		"Increases your Shadow spell damage by 2%.",
		"Increases your Shadow spell damage by 4%.",
		"Increases your Shadow spell damage by 6%.",
		"Increases your Shadow spell damage by 8%.",
		"Increases your Shadow spell damage by 10%."
		];
i++;
//Shadowform - Shadow
rank[i] = [
		"Cast: instant.<br>Cost: 40% of base mana.<br>Assume a Shadowform, increasing your Shadow damage by 15% and reducing physical damage done to you by 15%.  However, you may not cast Holy spells while in this form.  (Cooldown: 1.5 seconds.)"
		];
i++;

jsLoaded=true;